"""Highscore table

Revision ID: f13aa665be11
Revises: 
Create Date: 2020-10-21 17:11:18.330778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13aa665be11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highscore_score'), 'highscore', ['score'], unique=False)
    op.create_index(op.f('ix_highscore_username'), 'highscore', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highscore_username'), table_name='highscore')
    op.drop_index(op.f('ix_highscore_score'), table_name='highscore')
    op.drop_table('highscore')
    # ### end Alembic commands ###
